services:
  user:
    depends_on:
      db:
        condition: service_healthy
    user: bun
    image: oven/bun:1.1.18
    restart: unless-stopped
    working_dir: /usr/src/app
    command: sh -c "bun --watch app/services/user/index.ts"
    networks:
      - default
    ports:
      - '5000:5000'
    volumes:
      - ./:/usr/src/app
    environment:
      PORT: 5000
      SERVICE: User
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: app
      DATABASE_PASSWORD: password
      DATABASE_NAME: app

  db:
    image: mysql:8.3.0
    restart: unless-stopped
    networks:
      - default
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 5s
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
